# Generated by Django 4.2.23 on 2025-07-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
